### ISSUE TITLE
debug 404 and 500 error appearing around lobby on google (server side)

### ISSUE THREAD

**Issue by lindasteiner2** [sopra-fs23-group-24/server#74]
- [x] Fix 1: flex environment (based on OLAT forum)
- [ ] Fix 2: ignore 404, change deletion system in backend
- [ ] Fix 3: HTTP Streaming?

**Comment by tkinget** [comment]
2350131746592a47da602fd9eff383379294ee99 - changing to flex
ea5b2a47321fe01112e41ffa706af5752b4a3db9 - fixing bug
